# Generated by Django 4.1 on 2022-09-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantrana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profilePic', models.ImageField(upload_to='counsellor')),
                ('qualifications', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('expertise', models.CharField(choices=[('Career', 'Career'), ('Relationship', 'Relationship'), ('Legal Services', 'Legal Services')], max_length=100)),
                ('appointment', models.URLField()),
                ('insta', models.URLField()),
                ('facebook', models.URLField()),
            ],
        ),
    ]
