# Generated by Django 4.1 on 2022-09-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantrana', '0002_counsellors'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellors',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
